// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAzF7l0as6MKo4WYJ7JTt0l2McMCjnoOs',
    appId: '1:356916633694:web:1f509ddbfa10293a8a94cf',
    messagingSenderId: '356916633694',
    projectId: 'aetherbrowser-320eb',
    authDomain: 'aetherbrowser-320eb.firebaseapp.com',
    storageBucket: 'aetherbrowser-320eb.firebasestorage.app',
    measurementId: 'G-RWL306HQFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsbXvYpjzOrDYkgCj2iijAzljiX3t5qVw',
    appId: '1:356916633694:android:41f6c10a5b7d6d4d8a94cf',
    messagingSenderId: '356916633694',
    projectId: 'aetherbrowser-320eb',
    storageBucket: 'aetherbrowser-320eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOxHxcCnyk3oer5nYWaX_A8RNMe47NcBc',
    appId: '1:356916633694:ios:3269bf112f355c478a94cf',
    messagingSenderId: '356916633694',
    projectId: 'aetherbrowser-320eb',
    storageBucket: 'aetherbrowser-320eb.firebasestorage.app',
    iosBundleId: 'com.example.flutterStateManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOxHxcCnyk3oer5nYWaX_A8RNMe47NcBc',
    appId: '1:356916633694:ios:3269bf112f355c478a94cf',
    messagingSenderId: '356916633694',
    projectId: 'aetherbrowser-320eb',
    storageBucket: 'aetherbrowser-320eb.firebasestorage.app',
    iosBundleId: 'com.example.flutterStateManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAzF7l0as6MKo4WYJ7JTt0l2McMCjnoOs',
    appId: '1:356916633694:web:2084b4ee2652eb678a94cf',
    messagingSenderId: '356916633694',
    projectId: 'aetherbrowser-320eb',
    authDomain: 'aetherbrowser-320eb.firebaseapp.com',
    storageBucket: 'aetherbrowser-320eb.firebasestorage.app',
    measurementId: 'G-SPR29QBW90',
  );
}
